MYSEED: 0
alpha: 128
batch_size: 8
bins: 100
crop_size: !!python/tuple [480, 480]
cudaid: '0'
dataset: Caltech-UCSD-Birds-200-2011
epoch_start_erasing: 1
erase_in_inference: false
extension: !!python/tuple [jpeg, JPEG]
floating: 2
fold: 0
fold_folder: ./folds
height_tag: 50
img_extension: bmp
max_epochs: -1
model:
  alpha: 0.0
  dropout: 0.85
  kmax: 0.09
  kmin: 0.09
  modalities: 5
  name: resnet101
  num_classes: 5
  num_masks: 1
  pretrained: true
  scale: !!python/tuple [0.5, 0.5]
  sigma: 0.5
  w: 8
name_classes: encoding.yaml
nbr_classes: 5
nbr_times_erase: 4
normalize: true
num_workers: 8
optimizer:
  dampening: 0.0
  lr: 0.001
  lr_scheduler: {gamma: 0.1, last_epoch: -1, min_lr: 1.0e-07, name: mystep, step_size: 40}
  momentum: 0.9
  name: sgd
  nesterov: true
  weight_decay: 1.0e-05
pad_eval: false
padding_mode: reflect
padding_size: null
path_pre_trained: ../our-pretrained/cub5-4.pt
preload: true
rangeh: !!python/tuple [0, 1]
resize: null
show_hists: false
sigma_erase: 10
split: 0
strict: true
up_scale_small_dim_to: 500
use_tags: true
yaml: caltech-birds.yaml
